name: E1
on: push
jobs:
  deploy: 
    runs-on: ubuntu-latest  
    steps:
      - name: baixa codigo
        uses: actions/checkout@v3
      - name: instala dependencias
        run: npm ci
      - name: executa lint
        run: npm run lint
      - name: executa test
        run: npm run test
      - name: executa build
        run: npm run build
      - name: simula deploy
        run: echo "fazendo deploy"
